# Generated by Django 4.2.1 on 2023-05-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_image_url", models.URLField(blank=True)),
                ("company_name", models.CharField(max_length=100)),
            ],
        ),
    ]
