# Generated by Django 4.2.1 on 2023-05-19 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0005_alter_intro_img_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intro_img",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[django.core.validators.FileExtensionValidator(["jpg"])],
            ),
        ),
    ]
