# Generated by Django 4.2.1 on 2023-05-19 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0008_product1_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="product2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_p2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["png"])
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="product3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_p3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["png"])
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product1",
            name="image_p1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[django.core.validators.FileExtensionValidator(["png"])],
            ),
        ),
    ]
