# Generated by Django 4.2.1 on 2023-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0014_facebooklink"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedinLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Llink", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="facebooklink",
            name="F_Link",
        ),
    ]
